# Generated by Django 4.2.3 on 2023-07-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_servico', models.CharField(choices=[('LC', 'lavagem_completa'), ('ML', 'meia_lavagem')], db_column='escolha_servico', max_length=25)),
                ('aviso', models.CharField(db_column='aviso', max_length=60)),
                ('data_inicio', models.DateField()),
                ('veiculos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.veiculo')),
            ],
        ),
    ]
