# Generated by Django 4.2.3 on 2023-07-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='escolha_servico',
            field=models.CharField(choices=[('LC', 'lavagem_completa'), ('ML', 'meia_lavagem')], db_column='escolha_servico', max_length=2),
        ),
    ]
