# Generated by Django 4.2.3 on 2023-07-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0002_alter_servicos_escolha_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='veiculos',
        ),
        migrations.AddField(
            model_name='servicos',
            name='veiculos_serv',
            field=models.OneToOneField(db_column='veiculos_serv', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.veiculo'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='aviso',
            field=models.CharField(db_column='aviso', max_length=60, null=True),
        ),
    ]
