# Generated by Django 4.2.3 on 2023-07-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servicos_veiculo_alter_servicos_escolha_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
