# Generated by Django 4.2.3 on 2023-07-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=30)),
                ('telefone', models.CharField(db_column='telefone', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(choices=[('CC', 'CARRO'), ('CM', 'CAMINHONETE'), ('M', 'MOTO')], db_column='tipo_veiculo', default='CARRO', max_length=3)),
                ('placa', models.CharField(db_column='placa', max_length=8)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
