# Generated by Django 4.2.3 on 2023-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='serviço',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
