# Generated by Django 4.2.3 on 2023-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_veiculo_serviço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='veiculo',
            field=models.CharField(choices=[('CC', 'CARRO'), ('CM', 'CAMINHONETE'), ('M', 'MOTO')], db_column='tipo_veiculo', default='CC', max_length=3),
        ),
    ]
